apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
      - name: vue
        image: vue-kube
        imagePullPolicy: Never        # 👈 AJOUT IMPORTANT
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  type: NodePort
  selector:
    app: vue
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
